site_name: Recos Technical Documentation
site_url: https://recos-six.vercel.app/
theme:
  name: material
  logo: images/recos-logo.png
  favicon: images/recos-logo.png
  palette:
    primary: dark blue
    accent: deep purple
  font:
    text: Inter
    code: Fira Mono
  features:
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - search.highlight
    - search.suggest
    - search.share
  custom_dir: docs/styles


extra_css:
  - styles/extra.css

extra:
  footer: |
    <div style="background: #8645e8; color: #fff; padding: 24px 0; text-align: center; font-size: 1.15em; font-family: Inter, sans-serif;">
      <span style="font-weight: 600; font-size: 1.2em; color: #fff;">Created by <span style="color: #fff; letter-spacing: 2px;">Recos</span> &copy; 2025</span>
    </div>

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Features: features.md
  - How It Works: developer-docs.md
  - Integrations: integrations.md
  - API Reference: api-reference.md
  - Q/A Process: qa-process.md
  - Deployment Process: deployment-process.md
  - Code Standards: code-standards.md

